# SLU2 - Subsetting data: Learning notebook

In this notebook we will cover the following: 

    - Selecting columns (brackets and dot notation)
    - Selecting rows (loc and iloc)
    - Chain indexing (not good) vs Multi-axis indexing (good)
    - Masks
    - Where
    - Subsetting on conditions
    - Dtypes
    - Select Dtypes
    - nlargest
    - nsmallest

First, we import pandas, like we learned in the previous unit:

In [1]:
import pandas as pd

# This is an option to preview less rows in the notebook's cells' outputs
pd.options.display.max_rows = 10

Now, we read the data that we'll use in this unit from the file __airbnb_input.csv__, which is located in the __data/__ directory.

For this, we'll use function __read_csv( )__, which was alreay shown in the previous unit.
We want to use column __room_id__ as the DataFrame index, and for that we use the argument __index_col__ in function read_csv( ).

In [2]:
# Read the data in file airbnb_input.csv into a pandas DataFrame and use column room_id as the DataFrame index.
df = pd.read_csv('data/airbnb_input.csv', index_col='room_id')

# Preview the first rows of the DataFrame.
df.head()

host_id        room_type       neighborhood  reviews  \
room_id                                                         
6499       14455  Entire home/apt              Belém        8   
17031      66015  Entire home/apt           Alvalade        0   
25659     107347  Entire home/apt  Santa Maria Maior       63   
29248     125768  Entire home/apt  Santa Maria Maior      225   
29396     126415  Entire home/apt  Santa Maria Maior      132   

         overall_satisfaction  accommodates  bedrooms  price  
room_id                                                       
6499                      5.0             2       1.0   57.0  
17031                     0.0             2       1.0   46.0  
25659                     5.0             3       1.0   69.0  
29248                     4.5             4       1.0   58.0  
29396                     5.0             4       1.0   67.0

## Selecting columns

### Selecting columns by name - dot notation

Using __dot notation__, you can select a column from a DataFrame, obtaining a Series with the column values.

This is how you can select the room_type column using dot notation:

In [3]:
df.room_type

room_id
6499        Entire home/apt
17031       Entire home/apt
25659       Entire home/apt
29248       Entire home/apt
29396       Entire home/apt
                 ...       
19388006    Entire home/apt
19393935    Entire home/apt
19396300    Entire home/apt
19397373    Entire home/apt
19400722    Entire home/apt
Name: room_type, Length: 13232, dtype: object

### Selecting columns by name - brackets notation

Using __brackets__, you can select one or more columns from the DataFrame.

This is how you can select the room_type column using brackets. Note that the output is a Series:

In [4]:
df['room_type']

room_id
6499        Entire home/apt
17031       Entire home/apt
25659       Entire home/apt
29248       Entire home/apt
29396       Entire home/apt
                 ...       
19388006    Entire home/apt
19393935    Entire home/apt
19396300    Entire home/apt
19397373    Entire home/apt
19400722    Entire home/apt
Name: room_type, Length: 13232, dtype: object

This is how you can select the room_type and neighborhood columns using brackets. Note that the output is a DataFrame:

In [5]:
df[['room_type', 'neighborhood']]

room_type       neighborhood
room_id                                     
6499      Entire home/apt              Belém
17031     Entire home/apt           Alvalade
25659     Entire home/apt  Santa Maria Maior
29248     Entire home/apt  Santa Maria Maior
29396     Entire home/apt  Santa Maria Maior
...                   ...                ...
19388006  Entire home/apt        São Vicente
19393935  Entire home/apt  Santa Maria Maior
19396300  Entire home/apt      Santo António
19397373  Entire home/apt        São Vicente
19400722  Entire home/apt            Areeiro

[13232 rows x 2 columns]

## Selecting rows

### Selecting rows by index position - iloc

With function [iloc](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.iloc.html) you can select specific rows from a DataFrame.

In order to specify the rows you want to select you can use the row position (integer starting from 0), a list, or an array slice.

This is how you can select the first row (remember that Python starts indexing with a 0). Note that the output is a Series:

In [6]:
df.iloc[0]

host_id                           14455
room_type               Entire home/apt
neighborhood                      Belém
reviews                               8
overall_satisfaction                  5
accommodates                          2
bedrooms                              1
price                                57
Name: 6499, dtype: object

This is how you select rows 0, 2, 4 and 6. Note that the output is a DataFrame:

In [7]:
df.iloc[[0, 2, 4, 6]]

host_id        room_type       neighborhood  reviews  \
room_id                                                         
6499       14455  Entire home/apt              Belém        8   
25659     107347  Entire home/apt  Santa Maria Maior       63   
29396     126415  Entire home/apt  Santa Maria Maior      132   
29872     128698  Entire home/apt          Alcântara       25   

         overall_satisfaction  accommodates  bedrooms  price  
room_id                                                       
6499                      5.0             2       1.0   57.0  
25659                     5.0             3       1.0   69.0  
29396                     5.0             4       1.0   67.0  
29872                     5.0             2       1.0   75.0

This is how you select the first 3 rows:

In [8]:
df.iloc[:3]

host_id        room_type       neighborhood  reviews  \
room_id                                                         
6499       14455  Entire home/apt              Belém        8   
17031      66015  Entire home/apt           Alvalade        0   
25659     107347  Entire home/apt  Santa Maria Maior       63   

         overall_satisfaction  accommodates  bedrooms  price  
room_id                                                       
6499                      5.0             2       1.0   57.0  
17031                     0.0             2       1.0   46.0  
25659                     5.0             3       1.0   69.0

### Selecting rows by index name - loc

With function [loc](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.loc.html) you can select specific rows from a DataFrame, like with iloc.

The difference here is that you specify the rows to select using the rows' indexes instead of the rows' positions in the DataFrame.

This is how you select room 29396:

In [9]:
df.loc[29396]

host_id                            126415
room_type                 Entire home/apt
neighborhood            Santa Maria Maior
reviews                               132
overall_satisfaction                    5
accommodates                            4
bedrooms                                1
price                                  67
Name: 29396, dtype: object

Note that if you search for an index that doesn't exist, you'll get a KeyError:

In [10]:
df.loc[100]

KeyError: 'the label [100] is not in the [index]'

## A performance remark!

### Chain indexing vs Multi-axis indexing

Imagine you are asked to select the neighborhood of room 17031.

When we want to select a specific value in a DataFrame, given the row and the column, we might be tempted to do the following:

In [11]:
%%time
# This command is used to count the time that the code in this cell took to run

df['neighborhood'][17031]

CPU times: user 251 µs, sys: 116 µs, total: 367 µs
Wall time: 1.37 ms


'Alvalade'

However, as you can see, this is a faster solution:

In [12]:
%%time
df.loc[17031, 'neighborhood']

CPU times: user 81 µs, sys: 0 ns, total: 81 µs
Wall time: 87 µs


'Alvalade'

But why?

When we select a row or column in a DataFrame using brackets, the Python bellow Pandas is calling the \__getitem\__ method to return the requested data.

Well, when we chain two sets of brackets, as in the first example, we are calling the \__getitem\__ method twice! This is called __chain indexing__, and __should be avoided__!

On the other hand, when we use loc to select a value given a row and column at the same time, Python is only calling the \__getitem\__ method once. This is called __multi-axis indexing__, and should be used.

## Masks

The [mask](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.mask.html) function can be used to "hide" the rows that verify a certain condition.

The rows where the condition holds will have the values replaced by NaN:

In [13]:
df.mask(df.overall_satisfaction == 5.0)

host_id        room_type       neighborhood  reviews  \
room_id                                                              
6499              NaN              NaN                NaN      NaN   
17031         66015.0  Entire home/apt           Alvalade      0.0   
25659             NaN              NaN                NaN      NaN   
29248        125768.0  Entire home/apt  Santa Maria Maior    225.0   
29396             NaN              NaN                NaN      NaN   
...               ...              ...                ...      ...   
19388006  135915593.0  Entire home/apt        São Vicente      0.0   
19393935    5376796.0  Entire home/apt  Santa Maria Maior      0.0   
19396300    6115933.0  Entire home/apt      Santo António      0.0   
19397373   97139334.0  Entire home/apt        São Vicente      0.0   
19400722   28219108.0  Entire home/apt            Areeiro      0.0   

          overall_satisfaction  accommodates  bedrooms  price  
room_id                                                        
6499                       NaN           NaN       NaN    NaN  
17031                      0.0           2.0       1.0   46.0  
25659                      NaN           NaN       NaN    NaN  
29248                      4.5           4.0       1.0   58.0  
29396                      NaN           NaN       NaN    NaN  
...                        ...           ...       ...    ...  
19388006                   0.0           6.0       3.0  415.0  
19393935                   0.0           3.0       1.0   50.0  
19396300                   0.0           6.0       4.0  138.0  
19397373                   0.0           4.0       1.0   56.0  
19400722                   0.0           5.0       3.0   75.0  

[13232 rows x 8 columns]

## Where

And the [where](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.where.html) function can be used to hide the rows that __don't__ verify a certain condition.

The rows where the condition doesn't hold will have the values replaced by NaN:

In [14]:
df.where(df.overall_satisfaction == 5.0)

host_id        room_type       neighborhood  reviews  \
room_id                                                           
6499       14455.0  Entire home/apt              Belém      8.0   
17031          NaN              NaN                NaN      NaN   
25659     107347.0  Entire home/apt  Santa Maria Maior     63.0   
29248          NaN              NaN                NaN      NaN   
29396     126415.0  Entire home/apt  Santa Maria Maior    132.0   
...            ...              ...                ...      ...   
19388006       NaN              NaN                NaN      NaN   
19393935       NaN              NaN                NaN      NaN   
19396300       NaN              NaN                NaN      NaN   
19397373       NaN              NaN                NaN      NaN   
19400722       NaN              NaN                NaN      NaN   

          overall_satisfaction  accommodates  bedrooms  price  
room_id                                                        
6499                       5.0           2.0       1.0   57.0  
17031                      NaN           NaN       NaN    NaN  
25659                      5.0           3.0       1.0   69.0  
29248                      NaN           NaN       NaN    NaN  
29396                      5.0           4.0       1.0   67.0  
...                        ...           ...       ...    ...  
19388006                   NaN           NaN       NaN    NaN  
19393935                   NaN           NaN       NaN    NaN  
19396300                   NaN           NaN       NaN    NaN  
19397373                   NaN           NaN       NaN    NaN  
19400722                   NaN           NaN       NaN    NaN  

[13232 rows x 8 columns]

Basically __mask__ and __where__ do the opposite of each other!

## Subsetting data on conditions

Using brackets notation, we can use conditions to subset data from the DataFrame.

By doing this, we get a DataFrame that (most likelly) has a different shape from the initial one, i.e, it's only a subset of it's rows.

Note that this is different from what we saw in the mask/filter functions: these functions don't change the DataFame shape, instead, they just replace the values that we don't want with NaNs.

Here we're subsetting the DataFrame to get all the rooms in the Alvalade neighborhood.

Note the DataFrame shape!

In [15]:
df[df.neighborhood == 'Alvalade']

host_id        room_type neighborhood  reviews  \
room_id                                                      
17031         66015  Entire home/apt     Alvalade        0   
72807        378525     Private room     Alvalade        1   
108058       557442     Private room     Alvalade       24   
143882       697596  Entire home/apt     Alvalade        0   
172014       820718     Private room     Alvalade       77   
...             ...              ...          ...      ...   
19206346  131826194  Entire home/apt     Alvalade        0   
19225159   84062304     Private room     Alvalade        0   
19227195  134599148  Entire home/apt     Alvalade        0   
19266319   15462808  Entire home/apt     Alvalade        0   
19271004   48058268     Private room     Alvalade        0   

          overall_satisfaction  accommodates  bedrooms  price  
room_id                                                        
17031                      0.0             2       1.0   46.0  
72807                      0.0             1       1.0   29.0  
108058                     5.0             1       1.0   27.0  
143882                     0.0             3       2.0  577.0  
172014                     4.5             4       1.0   45.0  
...                        ...           ...       ...    ...  
19206346                   0.0             5       2.0   87.0  
19225159                   0.0             2       1.0   54.0  
19227195                   0.0             4       2.0   56.0  
19266319                   0.0             2       1.0   52.0  
19271004                   0.0             2       1.0   44.0  

[253 rows x 8 columns]

As another example, we're selecting the rooms in Alvalade, that have more than 10 reviews.

Note the parenthesis around each condition, they're required!

In [16]:
df[(df.neighborhood == 'Alvalade') & (df.reviews > 10)]

host_id        room_type neighborhood  reviews  \
room_id                                                      
108058       557442     Private room     Alvalade       24   
172014       820718     Private room     Alvalade       77   
172248       507901     Private room     Alvalade       38   
216881      1119812  Entire home/apt     Alvalade       22   
333919       507901     Private room     Alvalade       48   
...             ...              ...          ...      ...   
15044690   18671578  Entire home/apt     Alvalade       33   
15786593  102115202  Entire home/apt     Alvalade       22   
15839689   16844987  Entire home/apt     Alvalade       24   
16690259   63598544  Entire home/apt     Alvalade       16   
17221766  108559367     Private room     Alvalade       24   

          overall_satisfaction  accommodates  bedrooms  price  
room_id                                                        
108058                     5.0             1       1.0   27.0  
172014                     4.5             4       1.0   45.0  
172248                     4.5             2       1.0   29.0  
216881                     4.5             6       2.0   74.0  
333919                     4.0             3       1.0   40.0  
...                        ...           ...       ...    ...  
15044690                   5.0             3       1.0   52.0  
15786593                   5.0             5       2.0   57.0  
15839689                   5.0             4       2.0   58.0  
16690259                   5.0             2       1.0   58.0  
17221766                   5.0             1       1.0   23.0  

[89 rows x 8 columns]

## Data Types

DataFrames have a class attribute that shows us the data type of each column. It's called __dtypes__ and can be used like this:

In [17]:
df.dtypes

host_id                   int64
room_type                object
neighborhood             object
reviews                   int64
overall_satisfaction    float64
accommodates              int64
bedrooms                float64
price                   float64
dtype: object

Note that strings have the dtype __object__.

__Dtypes__ can also be used to subset DataFrames. For instance, this is how we select all the float64 columns from the DataFrame:

In [18]:
df.select_dtypes(include=['float64'])

overall_satisfaction  bedrooms  price
room_id                                        
6499                       5.0       1.0   57.0
17031                      0.0       1.0   46.0
25659                      5.0       1.0   69.0
29248                      4.5       1.0   58.0
29396                      5.0       1.0   67.0
...                        ...       ...    ...
19388006                   0.0       3.0  415.0
19393935                   0.0       1.0   50.0
19396300                   0.0       4.0  138.0
19397373                   0.0       1.0   56.0
19400722                   0.0       3.0   75.0

[13232 rows x 3 columns]

## nlargest and nsmallest

[nlargest](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.nlargest.html) is a function that can be used to select the n rows that have the largest values regarding certain column(s).

For instance, this is how we select the two rooms that had the highest number of reviews.

In [19]:
df.nlargest(n=2, columns='reviews')

host_id        room_type  neighborhood  reviews  \
room_id                                                    
176153    842219  Entire home/apt  Misericórdia      438   
1745355  9186518  Entire home/apt       Olivais      419   

         overall_satisfaction  accommodates  bedrooms  price  
room_id                                                       
176153                    5.0             4       2.0  102.0  
1745355                   4.5             5       2.0   50.0

[nsmallest](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.nsmallest.html)... 
Well, I'll let you extrapolate :)

But here's an example, where we sellect the 5 cheapest rooms:

In [20]:
df.nsmallest(n=5, columns='price')

host_id        room_type       neighborhood  reviews  \
room_id                                                           
1179457    5799522      Shared room      Santo António       42   
5557699   28812904      Shared room  Santa Maria Maior       22   
8422256   29862851     Private room           Alvalade        0   
13116032  72951043      Shared room            Arroios        1   
13342103   3518523  Entire home/apt  Santa Maria Maior       52   

          overall_satisfaction  accommodates  bedrooms  price  
room_id                                                        
1179457                    4.0            16       1.0   10.0  
5557699                    4.0             1       1.0   10.0  
8422256                    0.0             1       1.0   10.0  
13116032                   0.0             8       1.0   10.0  
13342103                   4.5             4       1.0   10.0